/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AlterForm: typeof import('./components/login/AlterForm.vue')['default']
    Button: typeof import('primevue/button')['default']
    CandlestickChart: typeof import('./modules/ListedCompany/components/CandlestickChart.vue')['default']
    Card: typeof import('primevue/card')['default']
    ConfirmDialog: typeof import('primevue/confirmdialog')['default']
    CrosshairChart: typeof import('./modules/ListedCompany/components/CrosshairChart.vue')['default']
    FeatureComingSoon: typeof import('./components/FeatureComingSoon.vue')['default']
    Form: typeof import('@primevue/forms/form')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    LineChart: typeof import('./modules/ListedCompany/components/LineChart.vue')['default']
    LoginForm: typeof import('./components/login/LoginForm.vue')['default']
    MainFooter: typeof import('./components/MainFooter.vue')['default']
    MainHeader: typeof import('./components/MainHeader.vue')['default']
    MainMenu: typeof import('./components/MainMenu.vue')['default']
    MainMenuItem: typeof import('./components/MainMenuItem.vue')['default']
    MainTopbar: typeof import('./components/MainTopbar.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    Message: typeof import('primevue/message')['default']
    Password: typeof import('primevue/password')['default']
    RegisterForm: typeof import('./components/login/RegisterForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StockChart: typeof import('./modules/ListedCompany/components/StockChart.vue')['default']
    StockDetailHeader: typeof import('./modules/ListedCompany/components/StockDetailHeader.vue')['default']
    StockDetailSidebar: typeof import('./modules/ListedCompany/components/StockDetailSidebar.vue')['default']
    StockRealtimeTab: typeof import('./modules/ListedCompany/components/StockRealtimeTab.vue')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    Tag: typeof import('primevue/tag')['default']
    Toast: typeof import('primevue/toast')['default']
  }
  export interface ComponentCustomProperties {
    StyleClass: typeof import('primevue/styleclass')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
